#Federico Carducci 22/02/2024 | creazione user dev_team specs
#user name: dev_team | host localhost | pw: caffeinecoders
CREATE USER 'dev_team'@'localhost' IDENTIFIED BY 'caffeinecoders';
GRANT Create role ON *.* TO 'dev_team'@'localhost';
GRANT Create user ON *.* TO 'dev_team'@'localhost';
GRANT Drop role ON *.* TO 'dev_team'@'localhost';
GRANT Event ON *.* TO 'dev_team'@'localhost';
GRANT File ON *.* TO 'dev_team'@'localhost';
GRANT Process ON *.* TO 'dev_team'@'localhost';
GRANT Reload ON *.* TO 'dev_team'@'localhost';
GRANT Replication client ON *.* TO 'dev_team'@'localhost';
GRANT Replication slave ON *.* TO 'dev_team'@'localhost';
GRANT Show databases ON *.* TO 'dev_team'@'localhost';
GRANT Shutdown ON *.* TO 'dev_team'@'localhost';
GRANT Super ON *.* TO 'dev_team'@'localhost';
GRANT Create tablespace ON *.* TO 'dev_team'@'localhost';
GRANT INNODB_REDO_LOG_ARCHIVE ON *.* TO 'dev_team'@'localhost';
GRANT ENCRYPTION_KEY_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT CONNECTION_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT TABLE_ENCRYPTION_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT ROLE_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT REPLICATION_SLAVE_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT BINLOG_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT AUDIT_ABORT_EXEMPT ON *.* TO 'dev_team'@'localhost';
GRANT SERVICE_CONNECTION_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT GROUP_REPLICATION_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT PASSWORDLESS_USER_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT XA_RECOVER_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT PERSIST_RO_VARIABLES_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT SHOW_ROUTINE ON *.* TO 'dev_team'@'localhost';
GRANT BACKUP_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT GROUP_REPLICATION_STREAM ON *.* TO 'dev_team'@'localhost';
GRANT CLONE_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT SESSION_VARIABLES_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT RESOURCE_GROUP_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT FIREWALL_EXEMPT ON *.* TO 'dev_team'@'localhost';
GRANT RESOURCE_GROUP_USER ON *.* TO 'dev_team'@'localhost';
GRANT BINLOG_ENCRYPTION_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT APPLICATION_PASSWORD_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT SYSTEM_USER ON *.* TO 'dev_team'@'localhost';
GRANT FLUSH_OPTIMIZER_COSTS ON *.* TO 'dev_team'@'localhost';
GRANT AUDIT_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT TELEMETRY_LOG_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT INNODB_REDO_LOG_ENABLE ON *.* TO 'dev_team'@'localhost';
GRANT REPLICATION_APPLIER ON *.* TO 'dev_team'@'localhost';
GRANT FLUSH_STATUS ON *.* TO 'dev_team'@'localhost';
GRANT FLUSH_USER_RESOURCES ON *.* TO 'dev_team'@'localhost';
GRANT FLUSH_TABLES ON *.* TO 'dev_team'@'localhost';
GRANT AUTHENTICATION_POLICY_ADMIN ON *.* TO 'dev_team'@'localhost';
GRANT SENSITIVE_VARIABLES_OBSERVER ON *.* TO 'dev_team'@'localhost';
GRANT SET_ANY_DEFINER ON *.* TO 'dev_team'@'localhost';
GRANT ALLOW_NONEXISTENT_DEFINER ON *.* TO 'dev_team'@'localhost';
GRANT TRANSACTION_GTID_TAG ON *.* TO 'dev_team'@'localhost';
GRANT Grant option ON *.* TO 'dev_team'@'localhost';
GRANT Alter routine ON *.* TO 'dev_team'@'localhost';
GRANT Create routine ON *.* TO 'dev_team'@'localhost';
GRANT Create temporary tables ON *.* TO 'dev_team'@'localhost';
GRANT Execute ON *.* TO 'dev_team'@'localhost';
GRANT Lock tables ON *.* TO 'dev_team'@'localhost';
GRANT Grant option ON *.* TO 'dev_team'@'localhost';
GRANT Alter ON *.* TO 'dev_team'@'localhost';
GRANT Create ON *.* TO 'dev_team'@'localhost';
GRANT Create view ON *.* TO 'dev_team'@'localhost';
GRANT Delete ON *.* TO 'dev_team'@'localhost';
GRANT Drop ON *.* TO 'dev_team'@'localhost';
GRANT Grant option ON *.* TO 'dev_team'@'localhost';
GRANT Index ON *.* TO 'dev_team'@'localhost';
GRANT Insert ON *.* TO 'dev_team'@'localhost';
GRANT References ON *.* TO 'dev_team'@'localhost';
GRANT Select ON *.* TO 'dev_team'@'localhost';
GRANT Show view ON *.* TO 'dev_team'@'localhost';
GRANT Trigger ON *.* TO 'dev_team'@'localhost';
GRANT Update ON *.* TO 'dev_team'@'localhost';

